# Generated by Django 5.2.15 on 2026-06-10 09:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=160)),
                ('telefone', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('assunto', models.CharField(max_length=160)),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Mensagem de contacto',
                'verbose_name_plural': 'Mensagens de contacto',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(blank=True, max_length=160)),
                ('telefone', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('comprovativo', models.FileField(blank=True, null=True, upload_to='doacoes/')),
                ('observacao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Doacao',
                'verbose_name_plural': 'Doacoes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=160)),
                ('tipo', models.CharField(choices=[('imagem', 'Imagem'), ('youtube', 'YouTube'), ('video', 'Video')], default='imagem', max_length=20)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='galeria/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'mov'])])),
                ('youtube_url', models.URLField(blank=True)),
                ('legenda', models.CharField(blank=True, max_length=255)),
                ('destaque', models.BooleanField(default=False)),
                ('publicado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Item da galeria',
                'verbose_name_plural': 'Galeria',
                'ordering': ['-destaque', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Subscritor da newsletter',
                'verbose_name_plural': 'Newsletter',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=140)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='parceiros/')),
                ('website', models.URLField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Parceiro',
                'verbose_name_plural': 'Parceiros',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(default='ACSOL - Acao de Solidariedade em Angola', max_length=160)),
                ('slogan', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('hero_titulo', models.CharField(blank=True, max_length=255)),
                ('hero_subtitulo', models.TextField(blank=True)),
                ('missao', models.TextField(blank=True)),
                ('visao', models.TextField(blank=True)),
                ('valores', models.TextField(blank=True)),
                ('telefone', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('whatsapp', models.CharField(blank=True, max_length=60)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Configuracao do site',
                'verbose_name_plural': 'Configuracoes do site',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=120)),
                ('valor', models.PositiveIntegerField(default=0)),
                ('sufixo', models.CharField(blank=True, max_length=20)),
                ('icone', models.CharField(blank=True, help_text='Classe Bootstrap Icons. Ex: bi-people-fill', max_length=80)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estatistica',
                'verbose_name_plural': 'Estatisticas',
                'ordering': ['ordem', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=140)),
                ('cargo', models.CharField(max_length=140)),
                ('biografia', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='equipa/')),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Membro da equipa',
                'verbose_name_plural': 'Equipa',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=160)),
                ('telefone', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('morada', models.CharField(blank=True, max_length=255)),
                ('profissao', models.CharField(blank=True, max_length=120)),
                ('area_interesse', models.CharField(max_length=160)),
                ('curriculo', models.FileField(blank=True, null=True, upload_to='curriculos/')),
                ('mensagem', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('novo', 'Novo'), ('analise', 'Em analise'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='novo', max_length=20)),
            ],
            options={
                'verbose_name': 'Candidatura de voluntario',
                'verbose_name_plural': 'Candidaturas de voluntarios',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('acao', models.CharField(max_length=180)),
                ('detalhe', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de atividade',
                'verbose_name_plural': 'Logs de atividade',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('projeto', 'Projeto'), ('noticia', 'Noticia'), ('evento', 'Evento'), ('galeria', 'Galeria'), ('faq', 'FAQ')], max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=140)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'unique_together': {('tipo', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('tipo', models.CharField(choices=[('noticia', 'Noticia'), ('evento', 'Evento')], default='noticia', max_length=20)),
                ('resumo', models.TextField()),
                ('conteudo', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='noticias/')),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('destaque', models.BooleanField(default=False)),
                ('publicado', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
            ],
            options={
                'verbose_name': 'Noticia ou evento',
                'verbose_name_plural': 'Noticias e eventos',
                'ordering': ['-data_publicacao', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pergunta', models.CharField(max_length=255)),
                ('resposta', models.TextField()),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'faq'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['ordem', 'pergunta'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('descricao', models.TextField()),
                ('objetivos', models.TextField(blank=True)),
                ('beneficiarios', models.PositiveIntegerField(default=0)),
                ('localizacao', models.CharField(blank=True, max_length=180)),
                ('estado', models.CharField(choices=[('planeado', 'Planeado'), ('andamento', 'Em andamento'), ('concluido', 'Concluido'), ('suspenso', 'Suspenso')], default='andamento', max_length=20)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='projetos/')),
                ('progresso', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('destaque', models.BooleanField(default=False)),
                ('publicado', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'projeto'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-destaque', '-criado_em'],
            },
        ),
    ]
