# Generated by Django 5.2.15 on 2026-06-10 10:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(default='Chatbot IA ACSOL', max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('provider', models.CharField(choices=[('llama', 'Llama API'), ('openai', 'OpenAI'), ('gemini', 'Gemini')], default='llama', max_length=20)),
                ('api_key', models.CharField(blank=True, help_text='Chave da API usada pelo chatbot.', max_length=255)),
                ('api_url', models.URLField(default='https://api.llama-api.com/chat/completions')),
                ('modelo', models.CharField(default='llama-3.1-8b-instruct', max_length=120)),
                ('mensagem_inicial', models.TextField(default='Ola! Sou o assistente virtual da ACSOL. Posso ajudar com projetos, voluntariado, eventos, doacoes e contactos.')),
                ('prompt_sistema', models.TextField(default='Responde apenas sobre a ACSOL Angola, projetos, voluntariado, eventos, doacoes e contactos. Se a pergunta fugir destes temas, explica educadamente que so podes responder sobre a ACSOL.')),
            ],
            options={
                'verbose_name': 'Chatbot IA',
                'verbose_name_plural': 'Chatbot IA',
            },
        ),
        migrations.CreateModel(
            name='DonationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(default='Como ajudar a ACSOL', max_length=160)),
                ('texto_publico', models.TextField(default='Escolha um valor, envie a sua intencao de doacao e recebera instrucoes seguras de pagamento.')),
                ('contacto_doacoes', models.EmailField(default='doacoes@acsol.ao', max_length=254)),
                ('telefone_doacoes', models.CharField(blank=True, max_length=60)),
                ('instrucoes_nacionais', models.TextField(blank=True)),
                ('instrucoes_internacionais', models.TextField(blank=True)),
                ('instrucoes_multicaixa', models.TextField(blank=True)),
                ('gateway_url', models.URLField(blank=True)),
                ('mostrar_dados_bancarios_publicamente', models.BooleanField(default=False, help_text='Manter desligado para nao expor dados bancarios na pagina principal.')),
            ],
            options={
                'verbose_name': 'Configuracao de doacoes',
                'verbose_name_plural': 'Configuracao de doacoes',
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='estado',
            field=models.CharField(choices=[('intencao', 'Intencao recebida'), ('instrucoes', 'Instrucoes enviadas'), ('comprovativo', 'Comprovativo recebido'), ('confirmada', 'Confirmada'), ('recibo', 'Recibo emitido'), ('cancelada', 'Cancelada')], default='intencao', max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='tipo',
            field=models.CharField(choices=[('nacional', 'Nacional'), ('internacional', 'Internacional'), ('multicaixa', 'Multicaixa Express'), ('gateway', 'Gateway online')], default='nacional', max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='comprovativo',
            field=models.FileField(blank=True, null=True, upload_to='doacoes/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.CreateModel(
            name='ChatbotFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pergunta', models.CharField(max_length=255)),
                ('resposta', models.TextField()),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='core.chatbotconfig')),
            ],
            options={
                'verbose_name': 'Pergunta frequente do chatbot',
                'verbose_name_plural': 'Perguntas frequentes do chatbot',
                'ordering': ['ordem', 'pergunta'],
            },
        ),
    ]
