# Generated by Django 5.2.15 on 2026-06-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chatbotconfig_donationsettings_donation_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationsettings',
            name='instrucoes_gateway',
            field=models.TextField(blank=True),
        ),
    ]
