# Generated by Django 5.2.15 on 2026-06-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_adminactionsnapshot_managernotification_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotconfig',
            name='assuntos_permitidos',
            field=models.TextField(default='ACSOL Angola, direitos humanos, projetos sociais, voluntariado, eventos, doacoes, contactos, protecao de criancas, familia, inclusao social', help_text='Usado quando o chatbot esta em modo restrito.'),
        ),
        migrations.AddField(
            model_name='chatbotconfig',
            name='idioma_voz',
            field=models.CharField(default='pt-PT', max_length=20),
        ),
        migrations.AddField(
            model_name='chatbotconfig',
            name='modo',
            field=models.CharField(choices=[('restrito', 'Restrito a ACSOL e direitos humanos'), ('livre', 'Livre')], default='restrito', max_length=20),
        ),
        migrations.AddField(
            model_name='chatbotconfig',
            name='voz_ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chatbotconfig',
            name='provider',
            field=models.CharField(choices=[('llama', 'Llama API'), ('openai', 'OpenAI'), ('gemini', 'Gemini'), ('openai_compat', 'API compativel com OpenAI')], default='llama', max_length=20),
        ),
    ]
