# Generated by Django 5.2.15 on 2026-06-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_provinceoffice'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationsettings',
            name='instrucoes_especie',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='tipo',
            field=models.CharField(choices=[('nacional', 'Nacional'), ('internacional', 'Internacional'), ('multicaixa', 'Multicaixa Express'), ('gateway', 'Gateway online'), ('especie', 'Doacao em especie')], default='nacional', max_length=20),
        ),
    ]
