# Generated by Django 5.2.15 on 2026-06-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_donationsettings_instrucoes_especie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InKindDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=60)),
                ('tipo_item', models.CharField(max_length=140)),
                ('quantidade', models.CharField(max_length=80)),
                ('estado_item', models.CharField(choices=[('novo', 'Novo'), ('usado_bom', 'Usado em bom estado'), ('usado_regular', 'Usado em estado regular')], default='novo', max_length=30)),
                ('descricao', models.TextField()),
                ('localizacao_entrega', models.CharField(max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='doacoes_especie/')),
                ('estado', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('recebida', 'Recebida'), ('distribuida', 'Distribuida'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=20)),
                ('familia_ou_projeto', models.CharField(blank=True, max_length=180)),
                ('observacao_admin', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Doacao em especie',
                'verbose_name_plural': 'Doacoes em especie',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SiteFlyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=160)),
                ('subtitulo', models.CharField(blank=True, max_length=255)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='flyers/')),
                ('posicao', models.CharField(choices=[('home', 'Inicio'), ('doacoes', 'Doacoes'), ('eventos', 'Eventos'), ('galeria', 'Galeria')], default='home', max_length=30)),
                ('link_texto', models.CharField(blank=True, max_length=80)),
                ('link_url', models.CharField(blank=True, max_length=180)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Flyer/banner',
                'verbose_name_plural': 'Flyers e banners',
                'ordering': ['posicao', 'ordem', 'titulo'],
            },
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='categoria',
            field=models.CharField(choices=[('projetos', 'Projetos'), ('eventos', 'Eventos'), ('voluntarios', 'Voluntarios'), ('comunidades', 'Comunidades'), ('outros', 'Outros')], default='outros', max_length=30),
        ),
    ]
