# Generated by Django 5.2.15 on 2026-06-11 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_inkinddonation_siteflyer_galleryitem_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedProject',
            fields=[
            ],
            options={
                'verbose_name': 'Projeto feito',
                'verbose_name_plural': 'Projetos feitos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.project',),
        ),
    ]
