# Generated by Django 5.2.15 on 2026-06-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_completedproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationsettings',
            name='doacoes_monetarias_ativas',
            field=models.BooleanField(default=False, help_text='Ligue apenas quando os dados bancarios e instrucoes oficiais estiverem confirmados.', verbose_name='Ativar Quero Doar'),
        ),
        migrations.AddField(
            model_name='donationsettings',
            name='mensagem_doacoes_indisponiveis',
            field=models.TextField(blank=True, default='A opcao Quero Doar esta temporariamente indisponivel enquanto a ACSOL confirma os dados bancarios oficiais. Para apoiar agora, contacte a equipa da ACSOL.', verbose_name='Mensagem quando Quero Doar estiver indisponivel'),
        ),
    ]
