# Generated by Django 5.2.15 on 2026-06-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_donationsettings_doacoes_monetarias_ativas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='imagem_sobre',
            field=models.ImageField(blank=True, help_text='Foto institucional usada na secao Quem Somos. Use uma imagem horizontal e bem enquadrada.', null=True, upload_to='site/', verbose_name='Imagem da secao Quem Somos'),
        ),
    ]
