# Generated by Django 5.2.15 on 2026-06-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_siteconfig_imagem_sobre'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='texto_parceiros',
            field=models.TextField(blank=True, default='A ACSOL trabalha em parceria com organizacoes governamentais, internacionais e do setor privado para maximizar o impacto das suas intervencoes.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='texto_valores',
            field=models.TextField(blank=True, default='', help_text='Texto introdutor opcional para a secao de valores.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='texto_voluntariado',
            field=models.TextField(blank=True, default='O voluntariado na ACSOL e uma experiencia transformadora. Contribui com as suas competencias, tempo e coracao para construir uma Angola melhor para todos.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='titulo_parceiros',
            field=models.CharField(default='Os Nossos Parceiros', max_length=160),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='titulo_valores',
            field=models.CharField(default='Os Nossos Valores', max_length=160),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='titulo_voluntariado',
            field=models.CharField(default='Porque Ser Voluntario?', max_length=160),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='valores_lista',
            field=models.TextField(blank=True, default='Solidariedade\nIntegridade\nInclusao\nInovacao\nResponsabilidade\nSustentabilidade', help_text='Um valor por linha. Exemplo: Solidariedade'),
        ),
    ]
